name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      -name: Deploy to EB
       uses: einaregilsson/beanstalk-deploy@v18
       with:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "AWS_ACCESS_KEY and AWS_SECRET_KEY have been set."
        application_name: Frontend-gh
        environment_name: Frontnend-env
        existing_bucket_name: elasticbeanstalk-us-east-1-739921103494
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip